// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package sdk

import (
	"context"

	"github.com/Khan/genqlient/graphql"
	"github.com/google/uuid"
)

// CreateResourceCreateResourceResourceResult includes the requested fields of the GraphQL type ResourceResult.
type CreateResourceCreateResourceResourceResult struct {
	Success  bool                                                         `json:"success"`
	Resource CreateResourceCreateResourceResourceResultResource           `json:"resource"`
	Error    CreateResourceCreateResourceResourceResultErrorMutationError `json:"error"`
}

// GetSuccess returns CreateResourceCreateResourceResourceResult.Success, and is useful for accessing the field via an interface.
func (v *CreateResourceCreateResourceResourceResult) GetSuccess() bool { return v.Success }

// GetResource returns CreateResourceCreateResourceResourceResult.Resource, and is useful for accessing the field via an interface.
func (v *CreateResourceCreateResourceResourceResult) GetResource() CreateResourceCreateResourceResourceResultResource {
	return v.Resource
}

// GetError returns CreateResourceCreateResourceResourceResult.Error, and is useful for accessing the field via an interface.
func (v *CreateResourceCreateResourceResourceResult) GetError() CreateResourceCreateResourceResourceResultErrorMutationError {
	return v.Error
}

// CreateResourceCreateResourceResourceResultErrorMutationError includes the requested fields of the GraphQL type MutationError.
// The GraphQL type's documentation follows.
//
// MutationError represents a business error occurred during a mutation.
type CreateResourceCreateResourceResourceResultErrorMutationError struct {
	Message string `json:"message"`
}

// GetMessage returns CreateResourceCreateResourceResourceResultErrorMutationError.Message, and is useful for accessing the field via an interface.
func (v *CreateResourceCreateResourceResourceResultErrorMutationError) GetMessage() string {
	return v.Message
}

// CreateResourceCreateResourceResourceResultResource includes the requested fields of the GraphQL type Resource.
type CreateResourceCreateResourceResourceResultResource struct {
	Id    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

// GetId returns CreateResourceCreateResourceResourceResultResource.Id, and is useful for accessing the field via an interface.
func (v *CreateResourceCreateResourceResourceResultResource) GetId() uuid.UUID { return v.Id }

// GetState returns CreateResourceCreateResourceResourceResultResource.State, and is useful for accessing the field via an interface.
func (v *CreateResourceCreateResourceResourceResultResource) GetState() string { return v.State }

type CreateResourceInput struct {
	TypeName     string                 `json:"typeName"`
	InitialState string                 `json:"initialState"`
	Metadata     map[string]interface{} `json:"metadata"`
}

// GetTypeName returns CreateResourceInput.TypeName, and is useful for accessing the field via an interface.
func (v *CreateResourceInput) GetTypeName() string { return v.TypeName }

// GetInitialState returns CreateResourceInput.InitialState, and is useful for accessing the field via an interface.
func (v *CreateResourceInput) GetInitialState() string { return v.InitialState }

// GetMetadata returns CreateResourceInput.Metadata, and is useful for accessing the field via an interface.
func (v *CreateResourceInput) GetMetadata() map[string]interface{} { return v.Metadata }

// CreateResourceResponse is returned by CreateResource on success.
type CreateResourceResponse struct {
	CreateResource CreateResourceCreateResourceResourceResult `json:"createResource"`
}

// GetCreateResource returns CreateResourceResponse.CreateResource, and is useful for accessing the field via an interface.
func (v *CreateResourceResponse) GetCreateResource() CreateResourceCreateResourceResourceResult {
	return v.CreateResource
}

// GetResourceResource includes the requested fields of the GraphQL type Resource.
type GetResourceResource struct {
	Id       uuid.UUID               `json:"id"`
	State    string                  `json:"state"`
	Metadata map[string]interface{}  `json:"metadata"`
	Type     GetResourceResourceType `json:"type"`
}

// GetId returns GetResourceResource.Id, and is useful for accessing the field via an interface.
func (v *GetResourceResource) GetId() uuid.UUID { return v.Id }

// GetState returns GetResourceResource.State, and is useful for accessing the field via an interface.
func (v *GetResourceResource) GetState() string { return v.State }

// GetMetadata returns GetResourceResource.Metadata, and is useful for accessing the field via an interface.
func (v *GetResourceResource) GetMetadata() map[string]interface{} { return v.Metadata }

// GetType returns GetResourceResource.Type, and is useful for accessing the field via an interface.
func (v *GetResourceResource) GetType() GetResourceResourceType { return v.Type }

// GetResourceResourceType includes the requested fields of the GraphQL type ResourceType.
type GetResourceResourceType struct {
	Name string `json:"name"`
}

// GetName returns GetResourceResourceType.Name, and is useful for accessing the field via an interface.
func (v *GetResourceResourceType) GetName() string { return v.Name }

// GetResourceResponse is returned by GetResource on success.
type GetResourceResponse struct {
	Resource GetResourceResource `json:"resource"`
}

// GetResource returns GetResourceResponse.Resource, and is useful for accessing the field via an interface.
func (v *GetResourceResponse) GetResource() GetResourceResource { return v.Resource }

// ListResourcesResourcesResourceConnection includes the requested fields of the GraphQL type ResourceConnection.
type ListResourcesResourcesResourceConnection struct {
	TotalCount int                                                         `json:"totalCount"`
	Edges      []ListResourcesResourcesResourceConnectionEdgesResourceEdge `json:"edges"`
	PageInfo   ListResourcesResourcesResourceConnectionPageInfo            `json:"pageInfo"`
}

// GetTotalCount returns ListResourcesResourcesResourceConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnection) GetTotalCount() int { return v.TotalCount }

// GetEdges returns ListResourcesResourcesResourceConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnection) GetEdges() []ListResourcesResourcesResourceConnectionEdgesResourceEdge {
	return v.Edges
}

// GetPageInfo returns ListResourcesResourcesResourceConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnection) GetPageInfo() ListResourcesResourcesResourceConnectionPageInfo {
	return v.PageInfo
}

// ListResourcesResourcesResourceConnectionEdgesResourceEdge includes the requested fields of the GraphQL type ResourceEdge.
type ListResourcesResourcesResourceConnectionEdgesResourceEdge struct {
	Cursor string                                                                `json:"cursor"`
	Node   ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource `json:"node"`
}

// GetCursor returns ListResourcesResourcesResourceConnectionEdgesResourceEdge.Cursor, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnectionEdgesResourceEdge) GetCursor() string {
	return v.Cursor
}

// GetNode returns ListResourcesResourcesResourceConnectionEdgesResourceEdge.Node, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnectionEdgesResourceEdge) GetNode() ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource {
	return v.Node
}

// ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource includes the requested fields of the GraphQL type Resource.
type ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource struct {
	Id    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

// GetId returns ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource.Id, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource) GetId() uuid.UUID {
	return v.Id
}

// GetState returns ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource.State, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnectionEdgesResourceEdgeNodeResource) GetState() string {
	return v.State
}

// ListResourcesResourcesResourceConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// PageInfo contains metadata about a paginated result.
type ListResourcesResourcesResourceConnectionPageInfo struct {
	HasNextPage bool   `json:"hasNextPage"`
	EndCursor   string `json:"endCursor"`
}

// GetHasNextPage returns ListResourcesResourcesResourceConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns ListResourcesResourcesResourceConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListResourcesResourcesResourceConnectionPageInfo) GetEndCursor() string { return v.EndCursor }

// ListResourcesResponse is returned by ListResources on success.
type ListResourcesResponse struct {
	Resources ListResourcesResourcesResourceConnection `json:"resources"`
}

// GetResources returns ListResourcesResponse.Resources, and is useful for accessing the field via an interface.
func (v *ListResourcesResponse) GetResources() ListResourcesResourcesResourceConnection {
	return v.Resources
}

type RegisterResourceTypeInput struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	JsonSchema  map[string]interface{} `json:"jsonSchema"`
	Transitions map[string]interface{} `json:"transitions"`
}

// GetName returns RegisterResourceTypeInput.Name, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeInput) GetName() string { return v.Name }

// GetDescription returns RegisterResourceTypeInput.Description, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeInput) GetDescription() string { return v.Description }

// GetJsonSchema returns RegisterResourceTypeInput.JsonSchema, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeInput) GetJsonSchema() map[string]interface{} { return v.JsonSchema }

// GetTransitions returns RegisterResourceTypeInput.Transitions, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeInput) GetTransitions() map[string]interface{} { return v.Transitions }

// RegisterResourceTypeRegisterResourceTypeResourceTypeResult includes the requested fields of the GraphQL type ResourceTypeResult.
type RegisterResourceTypeRegisterResourceTypeResourceTypeResult struct {
	Success      bool                                                                         `json:"success"`
	ResourceType RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType       `json:"resourceType"`
	Error        RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError `json:"error"`
}

// GetSuccess returns RegisterResourceTypeRegisterResourceTypeResourceTypeResult.Success, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeRegisterResourceTypeResourceTypeResult) GetSuccess() bool {
	return v.Success
}

// GetResourceType returns RegisterResourceTypeRegisterResourceTypeResourceTypeResult.ResourceType, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeRegisterResourceTypeResourceTypeResult) GetResourceType() RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType {
	return v.ResourceType
}

// GetError returns RegisterResourceTypeRegisterResourceTypeResourceTypeResult.Error, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeRegisterResourceTypeResourceTypeResult) GetError() RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError {
	return v.Error
}

// RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError includes the requested fields of the GraphQL type MutationError.
// The GraphQL type's documentation follows.
//
// MutationError represents a business error occurred during a mutation.
type RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError.Code, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError) GetCode() string {
	return v.Code
}

// GetMessage returns RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError.Message, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeRegisterResourceTypeResourceTypeResultErrorMutationError) GetMessage() string {
	return v.Message
}

// RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType includes the requested fields of the GraphQL type ResourceType.
type RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType struct {
	Id   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// GetId returns RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType.Id, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType) GetId() uuid.UUID {
	return v.Id
}

// GetName returns RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType.Name, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeRegisterResourceTypeResourceTypeResultResourceType) GetName() string {
	return v.Name
}

// RegisterResourceTypeResponse is returned by RegisterResourceType on success.
type RegisterResourceTypeResponse struct {
	RegisterResourceType RegisterResourceTypeRegisterResourceTypeResourceTypeResult `json:"registerResourceType"`
}

// GetRegisterResourceType returns RegisterResourceTypeResponse.RegisterResourceType, and is useful for accessing the field via an interface.
func (v *RegisterResourceTypeResponse) GetRegisterResourceType() RegisterResourceTypeRegisterResourceTypeResourceTypeResult {
	return v.RegisterResourceType
}

type TransitionResourceInput struct {
	ResourceId uuid.UUID              `json:"resourceId"`
	ToState    string                 `json:"toState"`
	Metadata   map[string]interface{} `json:"metadata"`
}

// GetResourceId returns TransitionResourceInput.ResourceId, and is useful for accessing the field via an interface.
func (v *TransitionResourceInput) GetResourceId() uuid.UUID { return v.ResourceId }

// GetToState returns TransitionResourceInput.ToState, and is useful for accessing the field via an interface.
func (v *TransitionResourceInput) GetToState() string { return v.ToState }

// GetMetadata returns TransitionResourceInput.Metadata, and is useful for accessing the field via an interface.
func (v *TransitionResourceInput) GetMetadata() map[string]interface{} { return v.Metadata }

// TransitionResourceResponse is returned by TransitionResource on success.
type TransitionResourceResponse struct {
	TransitionResource TransitionResourceTransitionResourceResourceResult `json:"transitionResource"`
}

// GetTransitionResource returns TransitionResourceResponse.TransitionResource, and is useful for accessing the field via an interface.
func (v *TransitionResourceResponse) GetTransitionResource() TransitionResourceTransitionResourceResourceResult {
	return v.TransitionResource
}

// TransitionResourceTransitionResourceResourceResult includes the requested fields of the GraphQL type ResourceResult.
type TransitionResourceTransitionResourceResourceResult struct {
	Success  bool                                                                 `json:"success"`
	Resource TransitionResourceTransitionResourceResourceResultResource           `json:"resource"`
	Error    TransitionResourceTransitionResourceResourceResultErrorMutationError `json:"error"`
}

// GetSuccess returns TransitionResourceTransitionResourceResourceResult.Success, and is useful for accessing the field via an interface.
func (v *TransitionResourceTransitionResourceResourceResult) GetSuccess() bool { return v.Success }

// GetResource returns TransitionResourceTransitionResourceResourceResult.Resource, and is useful for accessing the field via an interface.
func (v *TransitionResourceTransitionResourceResourceResult) GetResource() TransitionResourceTransitionResourceResourceResultResource {
	return v.Resource
}

// GetError returns TransitionResourceTransitionResourceResourceResult.Error, and is useful for accessing the field via an interface.
func (v *TransitionResourceTransitionResourceResourceResult) GetError() TransitionResourceTransitionResourceResourceResultErrorMutationError {
	return v.Error
}

// TransitionResourceTransitionResourceResourceResultErrorMutationError includes the requested fields of the GraphQL type MutationError.
// The GraphQL type's documentation follows.
//
// MutationError represents a business error occurred during a mutation.
type TransitionResourceTransitionResourceResourceResultErrorMutationError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns TransitionResourceTransitionResourceResourceResultErrorMutationError.Code, and is useful for accessing the field via an interface.
func (v *TransitionResourceTransitionResourceResourceResultErrorMutationError) GetCode() string {
	return v.Code
}

// GetMessage returns TransitionResourceTransitionResourceResourceResultErrorMutationError.Message, and is useful for accessing the field via an interface.
func (v *TransitionResourceTransitionResourceResourceResultErrorMutationError) GetMessage() string {
	return v.Message
}

// TransitionResourceTransitionResourceResourceResultResource includes the requested fields of the GraphQL type Resource.
type TransitionResourceTransitionResourceResourceResultResource struct {
	Id    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

// GetId returns TransitionResourceTransitionResourceResourceResultResource.Id, and is useful for accessing the field via an interface.
func (v *TransitionResourceTransitionResourceResourceResultResource) GetId() uuid.UUID { return v.Id }

// GetState returns TransitionResourceTransitionResourceResourceResultResource.State, and is useful for accessing the field via an interface.
func (v *TransitionResourceTransitionResourceResourceResultResource) GetState() string {
	return v.State
}

// __CreateResourceInput is used internally by genqlient
type __CreateResourceInput struct {
	Input CreateResourceInput `json:"input"`
}

// GetInput returns __CreateResourceInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateResourceInput) GetInput() CreateResourceInput { return v.Input }

// __GetResourceInput is used internally by genqlient
type __GetResourceInput struct {
	Id uuid.UUID `json:"id"`
}

// GetId returns __GetResourceInput.Id, and is useful for accessing the field via an interface.
func (v *__GetResourceInput) GetId() uuid.UUID { return v.Id }

// __ListResourcesInput is used internally by genqlient
type __ListResourcesInput struct {
	First    int    `json:"first"`
	After    string `json:"after"`
	TypeName string `json:"typeName"`
}

// GetFirst returns __ListResourcesInput.First, and is useful for accessing the field via an interface.
func (v *__ListResourcesInput) GetFirst() int { return v.First }

// GetAfter returns __ListResourcesInput.After, and is useful for accessing the field via an interface.
func (v *__ListResourcesInput) GetAfter() string { return v.After }

// GetTypeName returns __ListResourcesInput.TypeName, and is useful for accessing the field via an interface.
func (v *__ListResourcesInput) GetTypeName() string { return v.TypeName }

// __RegisterResourceTypeInput is used internally by genqlient
type __RegisterResourceTypeInput struct {
	Input RegisterResourceTypeInput `json:"input"`
}

// GetInput returns __RegisterResourceTypeInput.Input, and is useful for accessing the field via an interface.
func (v *__RegisterResourceTypeInput) GetInput() RegisterResourceTypeInput { return v.Input }

// __TransitionResourceInput is used internally by genqlient
type __TransitionResourceInput struct {
	Input TransitionResourceInput `json:"input"`
}

// GetInput returns __TransitionResourceInput.Input, and is useful for accessing the field via an interface.
func (v *__TransitionResourceInput) GetInput() TransitionResourceInput { return v.Input }

// The mutation executed by CreateResource.
const CreateResource_Operation = `
mutation CreateResource ($input: CreateResourceInput!) {
	createResource(input: $input) {
		success
		resource {
			id
			state
		}
		error {
			message
		}
	}
}
`

func CreateResource(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateResourceInput,
) (data_ *CreateResourceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateResource",
		Query:  CreateResource_Operation,
		Variables: &__CreateResourceInput{
			Input: input,
		},
	}

	data_ = &CreateResourceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetResource.
const GetResource_Operation = `
query GetResource ($id: UUID!) {
	resource(id: $id) {
		id
		state
		metadata
		type {
			name
		}
	}
}
`

func GetResource(
	ctx_ context.Context,
	client_ graphql.Client,
	id uuid.UUID,
) (data_ *GetResourceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetResource",
		Query:  GetResource_Operation,
		Variables: &__GetResourceInput{
			Id: id,
		},
	}

	data_ = &GetResourceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListResources.
const ListResources_Operation = `
query ListResources ($first: Int, $after: String, $typeName: String) {
	resources(first: $first, after: $after, typeName: $typeName) {
		totalCount
		edges {
			cursor
			node {
				id
				state
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func ListResources(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after string,
	typeName string,
) (data_ *ListResourcesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListResources",
		Query:  ListResources_Operation,
		Variables: &__ListResourcesInput{
			First:    first,
			After:    after,
			TypeName: typeName,
		},
	}

	data_ = &ListResourcesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by RegisterResourceType.
const RegisterResourceType_Operation = `
mutation RegisterResourceType ($input: RegisterResourceTypeInput!) {
	registerResourceType(input: $input) {
		success
		resourceType {
			id
			name
		}
		error {
			code
			message
		}
	}
}
`

func RegisterResourceType(
	ctx_ context.Context,
	client_ graphql.Client,
	input RegisterResourceTypeInput,
) (data_ *RegisterResourceTypeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "RegisterResourceType",
		Query:  RegisterResourceType_Operation,
		Variables: &__RegisterResourceTypeInput{
			Input: input,
		},
	}

	data_ = &RegisterResourceTypeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by TransitionResource.
const TransitionResource_Operation = `
mutation TransitionResource ($input: TransitionResourceInput!) {
	transitionResource(input: $input) {
		success
		resource {
			id
			state
		}
		error {
			code
			message
		}
	}
}
`

func TransitionResource(
	ctx_ context.Context,
	client_ graphql.Client,
	input TransitionResourceInput,
) (data_ *TransitionResourceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TransitionResource",
		Query:  TransitionResource_Operation,
		Variables: &__TransitionResourceInput{
			Input: input,
		},
	}

	data_ = &TransitionResourceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
