events { worker_connections 1024; }

http {
    upstream kors_api {
        # Round-robin distribution
        server kors-api:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://kors_api;
            # Force no keep-alive to see distribution in logs for this test
            proxy_set_header Connection "";
            proxy_http_version 1.1;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
