package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/google/uuid"
	"github.com/haksolot/kors/kors-api/internal/graph/generated"
	"github.com/haksolot/kors/kors-api/internal/graph/model"
)

// FindEventByID is the resolver for the findEventByID field.
func (r *entityResolver) FindEventByID(ctx context.Context, id uuid.UUID) (*model.Event, error) {
	e, err := r.ListEventsUseCase.Repo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if e == nil {
		return nil, nil
	}
	return &model.Event{
		ID:            e.ID,
		Type:          e.Type,
		Payload:       e.Payload,
		NatsMessageID: e.NatsMessageID,
		CreatedAt:     e.CreatedAt,
	}, nil
}

// FindIdentityByID is the resolver for the findIdentityByID field.
func (r *entityResolver) FindIdentityByID(ctx context.Context, id uuid.UUID) (*model.Identity, error) {
	ident, err := r.IdentityRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if ident == nil {
		return nil, nil
	}
	var extID *string
	if ident.ExternalID != "" {
		extID = &ident.ExternalID
	}
	return &model.Identity{
		ID:         ident.ID,
		ExternalID: extID,
		Name:       ident.Name,
		Type:       ident.Type,
		Metadata:   ident.Metadata,
		CreatedAt:  ident.CreatedAt,
		UpdatedAt:  ident.UpdatedAt,
	}, nil
}

// FindPermissionByID is the resolver for the findPermissionByID field.
func (r *entityResolver) FindPermissionByID(ctx context.Context, id uuid.UUID) (*model.Permission, error) {
	p, err := r.ListPermissionsUseCase.Repo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if p == nil {
		return nil, nil
	}
	return &model.Permission{
		ID:        p.ID,
		Action:    p.Action,
		ExpiresAt: p.ExpiresAt,
		CreatedAt: p.CreatedAt,
	}, nil
}

// FindResourceByID is the resolver for the findResourceByID field.
func (r *entityResolver) FindResourceByID(ctx context.Context, id uuid.UUID) (*model.Resource, error) {
	res, err := r.ListResourcesUseCase.Repo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}

	return &model.Resource{
		ID:        res.ID,
		State:     res.State,
		Metadata:  res.Metadata,
		CreatedAt: res.CreatedAt,
		UpdatedAt: res.UpdatedAt,
	}, nil
}

// FindResourceTypeByID is the resolver for the findResourceTypeByID field.
func (r *entityResolver) FindResourceTypeByID(ctx context.Context, id uuid.UUID) (*model.ResourceType, error) {
	rt, err := r.GetResourceTypeUseCase.Repo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if rt == nil {
		return nil, nil
	}
	desc := rt.Description
	return &model.ResourceType{
		ID:          rt.ID,
		Name:        rt.Name,
		Description: &desc,
		JSONSchema:  rt.JSONSchema,
		Transitions: rt.Transitions,
		CreatedAt:   rt.CreatedAt,
		UpdatedAt:   rt.UpdatedAt,
	}, nil
}

// FindRevisionByID is the resolver for the findRevisionByID field.
func (r *entityResolver) FindRevisionByID(ctx context.Context, id uuid.UUID) (*model.Revision, error) {
	rev, err := r.CreateRevisionUseCase.RevisionRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if rev == nil {
		return nil, nil
	}
	return &model.Revision{
		ID:        rev.ID,
		Snapshot:  rev.Snapshot,
		FilePath:  rev.FilePath,
		CreatedAt: rev.CreatedAt,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
