package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/safran-ls/kors/kors-api/internal/graph/generated"
	"github.com/safran-ls/kors/kors-api/internal/graph/model"
)

// FindEventByID is the resolver for the findEventByID field.
func (r *entityResolver) FindEventByID(ctx context.Context, id uuid.UUID) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: FindEventByID - findEventByID"))
}

// FindIdentityByID is the resolver for the findIdentityByID field.
func (r *entityResolver) FindIdentityByID(ctx context.Context, id uuid.UUID) (*model.Identity, error) {
	panic(fmt.Errorf("not implemented: FindIdentityByID - findIdentityByID"))
}

// FindPermissionByID is the resolver for the findPermissionByID field.
func (r *entityResolver) FindPermissionByID(ctx context.Context, id uuid.UUID) (*model.Permission, error) {
	panic(fmt.Errorf("not implemented: FindPermissionByID - findPermissionByID"))
}

// FindResourceByID is the resolver for the findResourceByID field.
func (r *entityResolver) FindResourceByID(ctx context.Context, id uuid.UUID) (*model.Resource, error) {
	res, err := r.ListResourcesUseCase.Repo.GetByID(ctx, id)
	if err != nil { return nil, err }
	if res == nil { return nil, nil }
	
	return &model.Resource{
		ID:        res.ID,
		State:     res.State,
		Metadata:  res.Metadata,
		CreatedAt: res.CreatedAt,
		UpdatedAt: res.UpdatedAt,
	}, nil
}

// FindResourceTypeByID is the resolver for the findResourceTypeByID field.
func (r *entityResolver) FindResourceTypeByID(ctx context.Context, id uuid.UUID) (*model.ResourceType, error) {
	panic(fmt.Errorf("not implemented: FindResourceTypeByID - findResourceTypeByID"))
}

// FindRevisionByID is the resolver for the findRevisionByID field.
func (r *entityResolver) FindRevisionByID(ctx context.Context, id uuid.UUID) (*model.Revision, error) {
	panic(fmt.Errorf("not implemented: FindRevisionByID - findRevisionByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
