package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/safran-ls/kors/kors-api/internal/graph/generated"
	"github.com/safran-ls/kors/kors-api/internal/graph/model"
	"github.com/safran-ls/kors/kors-api/internal/usecase"
)

// RegisterResourceType is the resolver for the registerResourceType field.
func (r *mutationResolver) RegisterResourceType(ctx context.Context, input model.RegisterResourceTypeInput) (*model.ResourceTypeResult, error) {
	// Execute usecase
	rt, err := r.RegisterResourceTypeUseCase.Execute(ctx, usecase.RegisterResourceTypeInput{
		Name:        input.Name,
		Description: *input.Description,
		JSONSchema:  input.JSONSchema,
		Transitions: input.Transitions,
	})
	if err != nil {
		return &model.ResourceTypeResult{
			Success: false,
			Error: &model.MutationError{
				Code:    "REGISTRATION_FAILED",
				Message: err.Error(),
			},
		}, nil
	}

	// Map domain to GraphQL model
	return &model.ResourceTypeResult{
		Success: true,
		ResourceType: &model.ResourceType{
			ID:          rt.ID,
			Name:        rt.Name,
			Description: &rt.Description,
			JSONSchema:  rt.JSONSchema,
			Transitions: rt.Transitions,
			CreatedAt:   rt.CreatedAt,
			UpdatedAt:   rt.UpdatedAt,
		},
	}, nil
}

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input model.CreateResourceInput) (*model.ResourceResult, error) {
	// Execute usecase
	res, err := r.CreateResourceUseCase.Execute(ctx, usecase.CreateResourceInput{
		TypeName:     input.TypeName,
		InitialState: input.InitialState,
		Metadata:     input.Metadata,
		IdentityID:   uuid.Nil,
	})
	if err != nil {
		return &model.ResourceResult{
			Success: false,
			Error: &model.MutationError{
				Code:    "CREATION_FAILED",
				Message: err.Error(),
			},
		}, nil
	}

	// Map domain to GraphQL model
	return &model.ResourceResult{
		Success: true,
		Resource: &model.Resource{
			ID:        res.ID,
			State:     res.State,
			Metadata:  res.Metadata,
			CreatedAt: res.CreatedAt,
			UpdatedAt: res.UpdatedAt,
			// Type will be resolved later (we need a field resolver)
		},
	}, nil
}

// TransitionResource is the resolver for the transitionResource field.
func (r *mutationResolver) TransitionResource(ctx context.Context, input model.TransitionResourceInput) (*model.ResourceResult, error) {
	// Execute usecase
	res, err := r.TransitionResourceUseCase.Execute(ctx, usecase.TransitionResourceInput{
		ResourceID: input.ResourceID,
		ToState:    input.ToState,
		Metadata:     input.Metadata,
		IdentityID:   uuid.Nil,
	})
	if err != nil {
		return &model.ResourceResult{
			Success: false,
			Error: &model.MutationError{
				Code:    "TRANSITION_FAILED",
				Message: err.Error(),
			},
		}, nil
	}

	// Map domain to GraphQL model
	return &model.ResourceResult{
		Success: true,
		Resource: &model.Resource{
			ID:        res.ID,
			State:     res.State,
			Metadata:  res.Metadata,
			CreatedAt: res.CreatedAt,
			UpdatedAt: res.UpdatedAt,
		},
	}, nil
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id uuid.UUID) (*model.Resource, error) {
	panic(fmt.Errorf("not implemented: Resource - resource"))
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, first *int, after *string, typeName *string) (*model.ResourceConnection, error) {
	panic(fmt.Errorf("not implemented: Resources - resources"))
}

// ResourceType is the resolver for the resourceType field.
func (r *queryResolver) ResourceType(ctx context.Context, name string) (*model.ResourceType, error) {
	panic(fmt.Errorf("not implemented: ResourceType - resourceType"))
}

// ResourceTypes is the resolver for the resourceTypes field.
func (r *queryResolver) ResourceTypes(ctx context.Context) ([]*model.ResourceType, error) {
	panic(fmt.Errorf("not implemented: ResourceTypes - resourceTypes"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
