package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/base64"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/nats-io/nats.go"
	"github.com/haksolot/kors/kors-api/internal/graph/generated"
	"github.com/haksolot/kors/kors-api/internal/graph/model"
	"github.com/haksolot/kors/kors-api/internal/usecase"
	"github.com/haksolot/kors/shared/korsctx"
)

func getIdentityID(ctx context.Context) uuid.UUID {
	id, ok := korsctx.FromContext(ctx)
	if !ok { return uuid.Nil }
	return id
}

// RegisterResourceType is the resolver for the registerResourceType field.
func (r *mutationResolver) RegisterResourceType(ctx context.Context, input model.RegisterResourceTypeInput) (*model.ResourceTypeResult, error) {
	rt, err := r.RegisterResourceTypeUseCase.Execute(ctx, usecase.RegisterResourceTypeInput{
		Name:        input.Name,
		Description: *input.Description,
		JSONSchema:  input.JSONSchema,
		Transitions: input.Transitions,
		IdentityID:  getIdentityID(ctx),
	})
	if err != nil { return &model.ResourceTypeResult{Success: false, Error: &model.MutationError{Code: "REGISTRATION_FAILED", Message: err.Error()}}, nil }
	return &model.ResourceTypeResult{Success: true, ResourceType: &model.ResourceType{ID: rt.ID, Name: rt.Name, Description: &rt.Description, JSONSchema: rt.JSONSchema, Transitions: rt.Transitions, CreatedAt: rt.CreatedAt, UpdatedAt: rt.UpdatedAt}}, nil
}

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input model.CreateResourceInput) (*model.ResourceResult, error) {
	res, err := r.CreateResourceUseCase.Execute(ctx, usecase.CreateResourceInput{
		TypeName:     input.TypeName,
		InitialState: input.InitialState,
		Metadata:     input.Metadata,
		IdentityID:   getIdentityID(ctx),
	})
	if err != nil { return &model.ResourceResult{Success: false, Error: &model.MutationError{Code: "CREATION_FAILED", Message: err.Error()}}, nil }
	return &model.ResourceResult{Success: true, Resource: &model.Resource{ID: res.ID, State: res.State, Metadata: res.Metadata, CreatedAt: res.CreatedAt, UpdatedAt: res.UpdatedAt}}, nil
}

// TransitionResource is the resolver for the transitionResource field.
func (r *mutationResolver) TransitionResource(ctx context.Context, input model.TransitionResourceInput) (*model.ResourceResult, error) {
	res, err := r.TransitionResourceUseCase.Execute(ctx, usecase.TransitionResourceInput{
		ResourceID: input.ResourceID,
		ToState:    input.ToState,
		Metadata:   input.Metadata,
		IdentityID: getIdentityID(ctx),
	})
	if err != nil { return &model.ResourceResult{Success: false, Error: &model.MutationError{Code: "TRANSITION_FAILED", Message: err.Error()}}, nil }
	return &model.ResourceResult{Success: true, Resource: &model.Resource{ID: res.ID, State: res.State, Metadata: res.Metadata, CreatedAt: res.CreatedAt, UpdatedAt: res.UpdatedAt}}, nil
}

// GrantPermission is the resolver for the grantPermission field.
func (r *mutationResolver) GrantPermission(ctx context.Context, input model.GrantPermissionInput) (*model.PermissionResult, error) {
	p, err := r.GrantPermissionUseCase.Execute(ctx, usecase.GrantPermissionInput{
		IdentityID:     input.IdentityID,
		ResourceID:     input.ResourceID,
		ResourceTypeID: input.ResourceTypeID,
		Action:         input.Action,
		ExpiresAt:      input.ExpiresAt,
	})
	if err != nil { return &model.PermissionResult{Success: false, Error: &model.MutationError{Code: "GRANT_FAILED", Message: err.Error()}}, nil }
	return &model.PermissionResult{Success: true, Permission: &model.Permission{ID: p.ID, Action: p.Action, ExpiresAt: p.ExpiresAt, CreatedAt: p.CreatedAt}}, nil
}

// CreateRevision is the resolver for the createRevision field.
func (r *mutationResolver) CreateRevision(ctx context.Context, input model.CreateRevisionInput) (*model.RevisionResult, error) {
	var fileContent []byte
	if input.FileContent != nil { fileContent, _ = base64.StdEncoding.DecodeString(*input.FileContent) }
	rev, err := r.CreateRevisionUseCase.Execute(ctx, usecase.CreateRevisionInput{
		ResourceID:  input.ResourceID,
		IdentityID:  getIdentityID(ctx),
		FileContent: fileContent,
		FileName:    *input.FileName,
	})
	if err != nil { return &model.RevisionResult{Success: false, Error: &model.MutationError{Code: "REVISION_FAILED", Message: err.Error()}}, nil }
	return &model.RevisionResult{Success: true, Revision: &model.Revision{ID: rev.ID, Snapshot: rev.Snapshot, FilePath: rev.FilePath, CreatedAt: rev.CreatedAt}}, nil
}

// ProvisionModule is the resolver for the provisionModule field.
func (r *mutationResolver) ProvisionModule(ctx context.Context, moduleName string) (*model.ProvisioningResult, error) {
	creds, err := r.ModuleGovernanceUseCase.Provision(ctx, moduleName, getIdentityID(ctx))
	if err != nil { return &model.ProvisioningResult{Success: false, Error: &model.MutationError{Code: "PROVISIONING_FAILED", Message: err.Error()}}, nil }
	return &model.ProvisioningResult{Success: true, ModuleName: &creds.ModuleName, Schema: &creds.Schema, Username: &creds.Username, Password: &creds.Password}, nil
}

// DeprovisionModule is the resolver for the deprovisionModule field.
func (r *mutationResolver) DeprovisionModule(ctx context.Context, moduleName string) (bool, error) {
	err := r.ModuleGovernanceUseCase.Deprovision(ctx, moduleName, getIdentityID(ctx))
	return err == nil, err
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id uuid.UUID) (*model.Resource, error) {
	return nil, nil
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, first *int, after *string, typeName *string) (*model.ResourceConnection, error) {
	limit := 20
	if first != nil { limit = *first }
	result, err := r.ListResourcesUseCase.Execute(ctx, usecase.ListResourcesInput{First: limit, After: after, TypeName: typeName})
	if err != nil { return nil, err }
	edges := make([]*model.ResourceEdge, len(result.Resources))
	for i, res := range result.Resources {
		edges[i] = &model.ResourceEdge{Cursor: res.ID.String(), Node: &model.Resource{ID: res.ID, State: res.State, Metadata: res.Metadata, CreatedAt: res.CreatedAt, UpdatedAt: res.UpdatedAt}}
	}
	var endCursor *string
	if len(edges) > 0 { c := edges[len(edges)-1].Cursor; endCursor = &c }
	return &model.ResourceConnection{Edges: edges, PageInfo: &model.PageInfo{HasNextPage: result.HasNextPage, EndCursor: endCursor}, TotalCount: result.TotalCount}, nil
}

// ResourceType is the resolver for the resourceType field.
func (r *queryResolver) ResourceType(ctx context.Context, name string) (*model.ResourceType, error) {
	return nil, nil
}

// ResourceTypes is the resolver for the resourceTypes field.
func (r *queryResolver) ResourceTypes(ctx context.Context) ([]*model.ResourceType, error) {
	return nil, nil
}

// ProvisionedModules is the resolver for the provisionedModules field.
func (r *queryResolver) ProvisionedModules(ctx context.Context) ([]string, error) {
	return r.ModuleGovernanceUseCase.List(ctx, getIdentityID(ctx))
}

// EventWasPublished is the resolver for the eventWasPublished field.
func (r *subscriptionResolver) EventWasPublished(ctx context.Context) (<-chan *model.Event, error) {
	events := make(chan *model.Event)
	sub, err := r.NatsConn.Subscribe("kors.>", func(msg *nats.Msg) {
		var gqlEvent model.Event
		if err := json.Unmarshal(msg.Data, &gqlEvent); err == nil {
			select { case events <- &gqlEvent: default: }
		}
	})
	if err != nil { return nil, err }
	go func() { <-ctx.Done(); sub.Unsubscribe(); close(events) }()
	return events, nil
}

// ResourceEvents is the resolver for the resourceEvents field.
func (r *subscriptionResolver) ResourceEvents(ctx context.Context, resourceID uuid.UUID) (<-chan *model.Event, error) {
	events := make(chan *model.Event)
	sub, err := r.NatsConn.Subscribe("kors.>", func(msg *nats.Msg) {
		var gqlEvent model.Event
		if err := json.Unmarshal(msg.Data, &gqlEvent); err == nil {
			if gqlEvent.Resource != nil && gqlEvent.Resource.ID == resourceID {
				select { case events <- &gqlEvent: default: }
			}
		}
	})
	if err != nil { return nil, err }
	go func() { <-ctx.Done(); sub.Unsubscribe(); close(events) }()
	return events, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
