package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/haksolot/kors/kors-api/internal/graph/generated"
	"github.com/haksolot/kors/kors-api/internal/graph/model"
	"github.com/haksolot/kors/kors-api/internal/usecase"
	"github.com/haksolot/kors/shared/pagination"
	nats "github.com/nats-io/nats.go"
)

// CreateIdentity is the resolver for the createIdentity field.
func (r *mutationResolver) CreateIdentity(ctx context.Context, input model.CreateIdentityInput) (*model.IdentityResult, error) {
	id, err := r.CreateIdentityUseCase.Execute(ctx, usecase.CreateIdentityInput{
		ExternalID: input.ExternalID,
		Name:       input.Name,
		Type:       input.Type,
		Metadata:   input.Metadata,
		CallerID:   getIdentityID(ctx),
	})
	if err != nil {
		return &model.IdentityResult{Success: false, Error: &model.MutationError{Code: "CREATION_FAILED", Message: err.Error()}}, nil
	}
	var extID *string
	if id.ExternalID != "" {
		extID = &id.ExternalID
	}
	return &model.IdentityResult{Success: true, Identity: &model.Identity{
		ID:         id.ID,
		ExternalID: extID,
		Name:       id.Name,
		Type:       id.Type,
		Metadata:   id.Metadata,
		CreatedAt:  id.CreatedAt,
		UpdatedAt:  id.UpdatedAt,
	}}, nil
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, id uuid.UUID) (*model.ResourceResult, error) {
	err := r.DeleteResourceUseCase.Execute(ctx, id, getIdentityID(ctx))
	if err != nil {
		return &model.ResourceResult{Success: false, Error: &model.MutationError{Code: "DELETE_FAILED", Message: err.Error()}}, nil
	}
	return &model.ResourceResult{Success: true}, nil
}

// RegisterResourceType is the resolver for the registerResourceType field.
func (r *mutationResolver) RegisterResourceType(ctx context.Context, input model.RegisterResourceTypeInput) (*model.ResourceTypeResult, error) {
	rt, err := r.RegisterResourceTypeUseCase.Execute(ctx, usecase.RegisterResourceTypeInput{
		Name:        input.Name,
		Description: *input.Description,
		JSONSchema:  input.JSONSchema,
		Transitions: input.Transitions,
		IdentityID:  getIdentityID(ctx),
	})
	if err != nil {
		return &model.ResourceTypeResult{Success: false, Error: &model.MutationError{Code: "REGISTRATION_FAILED", Message: err.Error()}}, nil
	}
	return &model.ResourceTypeResult{Success: true, ResourceType: &model.ResourceType{ID: rt.ID, Name: rt.Name, Description: &rt.Description, JSONSchema: rt.JSONSchema, Transitions: rt.Transitions, CreatedAt: rt.CreatedAt, UpdatedAt: rt.UpdatedAt}}, nil
}

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input model.CreateResourceInput) (*model.ResourceResult, error) {
	res, err := r.CreateResourceUseCase.Execute(ctx, usecase.CreateResourceInput{
		TypeName:     input.TypeName,
		InitialState: input.InitialState,
		Metadata:     input.Metadata,
		IdentityID:   getIdentityID(ctx),
	})
	if err != nil {
		return &model.ResourceResult{Success: false, Error: &model.MutationError{Code: "CREATION_FAILED", Message: err.Error()}}, nil
	}
	return &model.ResourceResult{Success: true, Resource: &model.Resource{ID: res.ID, State: res.State, Metadata: res.Metadata, CreatedAt: res.CreatedAt, UpdatedAt: res.UpdatedAt}}, nil
}

// TransitionResource is the resolver for the transitionResource field.
func (r *mutationResolver) TransitionResource(ctx context.Context, input model.TransitionResourceInput) (*model.ResourceResult, error) {
	res, err := r.TransitionResourceUseCase.Execute(ctx, usecase.TransitionResourceInput{
		ResourceID: input.ResourceID,
		ToState:    input.ToState,
		Metadata:   input.Metadata,
		IdentityID: getIdentityID(ctx),
	})
	if err != nil {
		return &model.ResourceResult{Success: false, Error: &model.MutationError{Code: "TRANSITION_FAILED", Message: err.Error()}}, nil
	}
	return &model.ResourceResult{Success: true, Resource: &model.Resource{ID: res.ID, State: res.State, Metadata: res.Metadata, CreatedAt: res.CreatedAt, UpdatedAt: res.UpdatedAt}}, nil
}

// GrantPermission is the resolver for the grantPermission field.
func (r *mutationResolver) GrantPermission(ctx context.Context, input model.GrantPermissionInput) (*model.PermissionResult, error) {
	p, err := r.GrantPermissionUseCase.Execute(ctx, usecase.GrantPermissionInput{
		IdentityID:     input.IdentityID,
		ResourceID:     input.ResourceID,
		ResourceTypeID: input.ResourceTypeID,
		Action:         input.Action,
		ExpiresAt:      input.ExpiresAt,
	})
	if err != nil {
		return &model.PermissionResult{Success: false, Error: &model.MutationError{Code: "GRANT_FAILED", Message: err.Error()}}, nil
	}
	return &model.PermissionResult{Success: true, Permission: &model.Permission{ID: p.ID, Action: p.Action, ExpiresAt: p.ExpiresAt, CreatedAt: p.CreatedAt}}, nil
}

// CreateRevision is the resolver for the createRevision field.
func (r *mutationResolver) CreateRevision(ctx context.Context, input model.CreateRevisionInput) (*model.RevisionResult, error) {
	var fileContent []byte
	if input.FileContent != nil {
		fileContent, _ = base64.StdEncoding.DecodeString(*input.FileContent)
	}
	rev, err := r.CreateRevisionUseCase.Execute(ctx, usecase.CreateRevisionInput{
		ResourceID:  input.ResourceID,
		IdentityID:  getIdentityID(ctx),
		FileContent: fileContent,
		FileName:    *input.FileName,
	})
	if err != nil {
		return &model.RevisionResult{Success: false, Error: &model.MutationError{Code: "REVISION_FAILED", Message: err.Error()}}, nil
	}
	return &model.RevisionResult{Success: true, Revision: &model.Revision{ID: rev.ID, Snapshot: rev.Snapshot, FilePath: rev.FilePath, CreatedAt: rev.CreatedAt}}, nil
}

// ProvisionModule is the resolver for the provisionModule field.
func (r *mutationResolver) ProvisionModule(ctx context.Context, moduleName string) (*model.ProvisioningResult, error) {
	creds, err := r.ModuleGovernanceUseCase.Provision(ctx, moduleName, getIdentityID(ctx))
	if err != nil {
		return &model.ProvisioningResult{Success: false, Error: &model.MutationError{Code: "PROVISIONING_FAILED", Message: err.Error()}}, nil
	}
	return &model.ProvisioningResult{Success: true, ModuleName: &creds.ModuleName, Schema: &creds.Schema, Username: &creds.Username, Password: &creds.Password}, nil
}

// DeprovisionModule is the resolver for the deprovisionModule field.
func (r *mutationResolver) DeprovisionModule(ctx context.Context, moduleName string) (bool, error) {
	err := r.ModuleGovernanceUseCase.Deprovision(ctx, moduleName, getIdentityID(ctx))
	return err == nil, err
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, input model.UploadFileInput) (*model.UploadResult, error) {
	out, err := r.UploadFileUseCase.Execute(ctx, usecase.UploadFileInput{
		FileName:    input.FileName,
		FileContent: input.FileContent,
		ContentType: *input.ContentType,
	})
	if err != nil {
		return &model.UploadResult{
			Success: false,
			Error:   &model.MutationError{Code: "UPLOAD_FAILED", Message: err.Error()},
		}, nil
	}
	if !out.Success {
		return &model.UploadResult{
			Success: false,
			Error:   &model.MutationError{Code: "UPLOAD_REJECTED", Message: out.Error},
		}, nil
	}
	return &model.UploadResult{
		Success:  true,
		URL:      &out.URL,
		FilePath: &out.FilePath,
	}, nil
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id uuid.UUID) (*model.Resource, error) {
	res, err := r.GetResourceUseCase.Execute(ctx, id, getIdentityID(ctx))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return &model.Resource{ID: res.ID, State: res.State, Metadata: res.Metadata, CreatedAt: res.CreatedAt, UpdatedAt: res.UpdatedAt}, nil
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, first *int, after *string, typeName *string) (*model.ResourceConnection, error) {
	limit := 20
	if first != nil {
		limit = *first
	}
	result, err := r.ListResourcesUseCase.Execute(ctx, usecase.ListResourcesInput{First: limit, After: after, TypeName: typeName})
	if err != nil {
		return nil, err
	}
	edges := make([]*model.ResourceEdge, len(result.Resources))
	for i, res := range result.Resources {
		edges[i] = &model.ResourceEdge{Cursor: pagination.EncodeCursor(res.ID.String()), Node: &model.Resource{ID: res.ID, State: res.State, Metadata: res.Metadata, CreatedAt: res.CreatedAt, UpdatedAt: res.UpdatedAt}}
	}
	var endCursor *string
	if len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}
	return &model.ResourceConnection{Edges: edges, PageInfo: &model.PageInfo{HasNextPage: result.HasNextPage, EndCursor: endCursor}, TotalCount: result.TotalCount}, nil
}

// ResourceType is the resolver for the resourceType field.
func (r *queryResolver) ResourceType(ctx context.Context, name string) (*model.ResourceType, error) {
	rt, err := r.GetResourceTypeUseCase.ExecuteByName(ctx, name)
	if err != nil {
		return nil, err
	}
	if rt == nil {
		return nil, nil
	}
	description := rt.Description
	return &model.ResourceType{ID: rt.ID, Name: rt.Name, Description: &description, JSONSchema: rt.JSONSchema, Transitions: rt.Transitions, CreatedAt: rt.CreatedAt, UpdatedAt: rt.UpdatedAt}, nil
}

// ResourceTypes is the resolver for the resourceTypes field.
func (r *queryResolver) ResourceTypes(ctx context.Context) ([]*model.ResourceType, error) {
	rts, err := r.GetResourceTypeUseCase.ExecuteList(ctx)
	if err != nil {
		return nil, err
	}
	var res []*model.ResourceType
	for _, rt := range rts {
		description := rt.Description
		res = append(res, &model.ResourceType{ID: rt.ID, Name: rt.Name, Description: &description, JSONSchema: rt.JSONSchema, Transitions: rt.Transitions, CreatedAt: rt.CreatedAt, UpdatedAt: rt.UpdatedAt})
	}
	return res, nil
}

// ProvisionedModules is the resolver for the provisionedModules field.
func (r *queryResolver) ProvisionedModules(ctx context.Context) ([]string, error) {
	return r.ModuleGovernanceUseCase.List(ctx, getIdentityID(ctx))
}

// Revisions is the resolver for the revisions field.
func (r *resourceResolver) Revisions(ctx context.Context, obj *model.Resource, first *int, after *string) (*model.RevisionConnection, error) {
	limit := 20
	if first != nil {
		limit = *first
	}
	var afterID *uuid.UUID
	if after != nil {
		rawID, err := pagination.DecodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid cursor: %w", err)
		}
		id, err := uuid.Parse(rawID)
		if err != nil {
			return nil, fmt.Errorf("invalid cursor ID: %w", err)
		}
		afterID = &id
	}

	revs, hasNext, total, err := r.CreateRevisionUseCase.RevisionRepo.ListByResourcePaginated(ctx, obj.ID, limit, afterID)
	if err != nil {
		return nil, err
	}

	edges := make([]*model.RevisionEdge, len(revs))
	for i, rev := range revs {
		edges[i] = &model.RevisionEdge{
			Cursor: pagination.EncodeCursor(rev.ID.String()),
			Node: &model.Revision{
				ID:        rev.ID,
				Resource:  obj,
				Identity:  &model.Identity{ID: rev.IdentityID},
				Snapshot:  rev.Snapshot,
				FilePath:  rev.FilePath,
				CreatedAt: rev.CreatedAt,
			},
		}
	}
	
	var endCursor *string
	if len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}
	
	return &model.RevisionConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
			EndCursor: endCursor,
		},
		TotalCount: total,
	}, nil
}

// EventWasPublished is the resolver for the eventWasPublished field.
func (r *subscriptionResolver) EventWasPublished(ctx context.Context) (<-chan *model.Event, error) {
	events := make(chan *model.Event)
	sub, err := r.NatsConn.Subscribe("kors.>", func(msg *nats.Msg) {
		var gqlEvent model.Event
		if err := json.Unmarshal(msg.Data, &gqlEvent); err == nil {
			select {
			case events <- &gqlEvent:
			default:
			}
		}
	})
	if err != nil {
		return nil, err
	}
	go func() { <-ctx.Done(); sub.Unsubscribe(); close(events) }()
	return events, nil
}

// ResourceEvents is the resolver for the resourceEvents field.
func (r *subscriptionResolver) ResourceEvents(ctx context.Context, resourceID uuid.UUID) (<-chan *model.Event, error) {
	events := make(chan *model.Event)
	sub, err := r.NatsConn.Subscribe("kors.>", func(msg *nats.Msg) {
		var gqlEvent model.Event
		if err := json.Unmarshal(msg.Data, &gqlEvent); err == nil {
			if gqlEvent.Resource != nil && gqlEvent.Resource.ID == resourceID {
				select {
				case events <- &gqlEvent:
				default:
				}
			}
		}
	})
	if err != nil {
		return nil, err
	}
	go func() { <-ctx.Done(); sub.Unsubscribe(); close(events) }()
	return events, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Resource returns generated.ResourceResolver implementation.
func (r *Resolver) Resource() generated.ResourceResolver { return &resourceResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type resourceResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
