// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type CreateResourceInput struct {
	TypeName     string         `json:"typeName"`
	InitialState string         `json:"initialState"`
	Metadata     map[string]any `json:"metadata,omitempty"`
}

type CreateRevisionInput struct {
	ResourceID  uuid.UUID `json:"resourceId"`
	FileContent *string   `json:"fileContent,omitempty"`
	FileName    *string   `json:"fileName,omitempty"`
}

type Event struct {
	ID            uuid.UUID      `json:"id"`
	Resource      *Resource      `json:"resource,omitempty"`
	Identity      *Identity      `json:"identity"`
	Type          string         `json:"type"`
	Payload       map[string]any `json:"payload"`
	NatsMessageID *uuid.UUID     `json:"natsMessageId,omitempty"`
	CreatedAt     time.Time      `json:"createdAt"`
}

func (Event) IsEntity() {}

type GrantPermissionInput struct {
	IdentityID     uuid.UUID  `json:"identityId"`
	ResourceID     *uuid.UUID `json:"resourceId,omitempty"`
	ResourceTypeID *uuid.UUID `json:"resourceTypeId,omitempty"`
	Action         string     `json:"action"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
}

type Identity struct {
	ID         uuid.UUID      `json:"id"`
	ExternalID *string        `json:"externalId,omitempty"`
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	Metadata   map[string]any `json:"metadata,omitempty"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
}

func (Identity) IsEntity() {}

type Mutation struct {
}

type MutationError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Permission struct {
	ID           uuid.UUID     `json:"id"`
	Identity     *Identity     `json:"identity"`
	Resource     *Resource     `json:"resource,omitempty"`
	ResourceType *ResourceType `json:"resourceType,omitempty"`
	Action       string        `json:"action"`
	ExpiresAt    *time.Time    `json:"expiresAt,omitempty"`
	CreatedAt    time.Time     `json:"createdAt"`
}

func (Permission) IsEntity() {}

type PermissionResult struct {
	Success    bool           `json:"success"`
	Permission *Permission    `json:"permission,omitempty"`
	Error      *MutationError `json:"error,omitempty"`
}

type ProvisioningResult struct {
	Success    bool           `json:"success"`
	ModuleName *string        `json:"moduleName,omitempty"`
	Schema     *string        `json:"schema,omitempty"`
	Username   *string        `json:"username,omitempty"`
	Password   *string        `json:"password,omitempty"`
	Error      *MutationError `json:"error,omitempty"`
}

type Query struct {
}

type RegisterResourceTypeInput struct {
	Name        string         `json:"name"`
	Description *string        `json:"description,omitempty"`
	JSONSchema  map[string]any `json:"jsonSchema"`
	Transitions map[string]any `json:"transitions"`
}

type Resource struct {
	ID        uuid.UUID      `json:"id"`
	Type      *ResourceType  `json:"type"`
	State     string         `json:"state"`
	Metadata  map[string]any `json:"metadata"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Revisions []*Revision    `json:"revisions"`
}

func (Resource) IsEntity() {}

type ResourceConnection struct {
	Edges      []*ResourceEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type ResourceEdge struct {
	Cursor string    `json:"cursor"`
	Node   *Resource `json:"node"`
}

type ResourceResult struct {
	Success  bool           `json:"success"`
	Resource *Resource      `json:"resource,omitempty"`
	Error    *MutationError `json:"error,omitempty"`
}

type ResourceType struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description *string        `json:"description,omitempty"`
	JSONSchema  map[string]any `json:"jsonSchema"`
	Transitions map[string]any `json:"transitions"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

func (ResourceType) IsEntity() {}

type ResourceTypeResult struct {
	Success      bool           `json:"success"`
	ResourceType *ResourceType  `json:"resourceType,omitempty"`
	Error        *MutationError `json:"error,omitempty"`
}

type Revision struct {
	ID          uuid.UUID      `json:"id"`
	Resource    *Resource      `json:"resource"`
	Identity    *Identity      `json:"identity"`
	Snapshot    map[string]any `json:"snapshot"`
	FilePath    *string        `json:"filePath,omitempty"`
	DownloadURL *string        `json:"downloadUrl,omitempty"`
	CreatedAt   time.Time      `json:"createdAt"`
}

func (Revision) IsEntity() {}

type RevisionResult struct {
	Success  bool           `json:"success"`
	Revision *Revision      `json:"revision,omitempty"`
	Error    *MutationError `json:"error,omitempty"`
}

type Subscription struct {
}

type TransitionResourceInput struct {
	ResourceID uuid.UUID      `json:"resourceId"`
	ToState    string         `json:"toState"`
	Metadata   map[string]any `json:"metadata,omitempty"`
}

type UploadFileInput struct {
	FileName    string  `json:"fileName"`
	FileContent string  `json:"fileContent"`
	ContentType *string `json:"contentType,omitempty"`
}

type UploadResult struct {
	Success  bool           `json:"success"`
	URL      *string        `json:"url,omitempty"`
	FilePath *string        `json:"filePath,omitempty"`
	Error    *MutationError `json:"error,omitempty"`
}
