# Generated by ariadne-codegen
# Source: operations.graphql

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .create_resource import CreateResource
from .get_resource import GetResource
from .input_types import (
    CreateResourceInput,
    RegisterResourceTypeInput,
    TransitionResourceInput,
)
from .list_resources import ListResources
from .register_resource_type import RegisterResourceType
from .transition_resource import TransitionResource


def gql(q: str) -> str:
    return q


class KorsClient(AsyncBaseClient):
    async def register_resource_type(
        self, input: RegisterResourceTypeInput, **kwargs: Any
    ) -> RegisterResourceType:
        query = gql("""
            mutation RegisterResourceType($input: RegisterResourceTypeInput!) {
              registerResourceType(input: $input) {
                success
                resourceType {
                  id
                  name
                }
                error {
                  code
                  message
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="RegisterResourceType",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return RegisterResourceType.model_validate(data)

    async def create_resource(
        self, input: CreateResourceInput, **kwargs: Any
    ) -> CreateResource:
        query = gql("""
            mutation CreateResource($input: CreateResourceInput!) {
              createResource(input: $input) {
                success
                resource {
                  id
                  state
                }
                error {
                  message
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateResource", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateResource.model_validate(data)

    async def transition_resource(
        self, input: TransitionResourceInput, **kwargs: Any
    ) -> TransitionResource:
        query = gql("""
            mutation TransitionResource($input: TransitionResourceInput!) {
              transitionResource(input: $input) {
                success
                resource {
                  id
                  state
                }
                error {
                  code
                  message
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="TransitionResource",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return TransitionResource.model_validate(data)

    async def get_resource(self, id: str, **kwargs: Any) -> GetResource:
        query = gql("""
            query GetResource($id: UUID!) {
              resource(id: $id) {
                id
                state
                metadata
                type {
                  name
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetResource", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetResource.model_validate(data)

    async def list_resources(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        type_name: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListResources:
        query = gql("""
            query ListResources($first: Int, $after: String, $typeName: String) {
              resources(first: $first, after: $after, typeName: $typeName) {
                totalCount
                edges {
                  cursor
                  node {
                    id
                    state
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "first": first,
            "after": after,
            "typeName": type_name,
        }
        response = await self.execute(
            query=query, operation_name="ListResources", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListResources.model_validate(data)
