# Generated by ariadne-codegen
# Source: operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateResource(BaseModel):
    create_resource: "CreateResourceCreateResource" = Field(alias="createResource")


class CreateResourceCreateResource(BaseModel):
    success: bool
    resource: Optional["CreateResourceCreateResourceResource"]
    error: Optional["CreateResourceCreateResourceError"]


class CreateResourceCreateResourceResource(BaseModel):
    id: str
    state: str


class CreateResourceCreateResourceError(BaseModel):
    message: str


CreateResource.model_rebuild()
CreateResourceCreateResource.model_rebuild()
