# Generated by ariadne-codegen
# Source: operations.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetResource(BaseModel):
    resource: Optional["GetResourceResource"]


class GetResourceResource(BaseModel):
    id: str
    state: str
    metadata: Any
    type_: "GetResourceResourceType" = Field(alias="type")


class GetResourceResourceType(BaseModel):
    name: str


GetResource.model_rebuild()
GetResourceResource.model_rebuild()
