# Generated by ariadne-codegen
# Source: ../../shared/schema/kors.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateResourceInput(BaseModel):
    type_name: str = Field(alias="typeName")
    initial_state: str = Field(alias="initialState")
    metadata: Optional[Any] = None


class TransitionResourceInput(BaseModel):
    resource_id: str = Field(alias="resourceId")
    to_state: str = Field(alias="toState")
    metadata: Optional[Any] = None


class RegisterResourceTypeInput(BaseModel):
    name: str
    description: Optional[str] = None
    json_schema: Any = Field(alias="jsonSchema")
    transitions: Any


class GrantPermissionInput(BaseModel):
    identity_id: str = Field(alias="identityId")
    resource_id: Optional[str] = Field(alias="resourceId", default=None)
    resource_type_id: Optional[str] = Field(alias="resourceTypeId", default=None)
    action: str
    expires_at: Optional[str] = Field(alias="expiresAt", default=None)


class CreateRevisionInput(BaseModel):
    resource_id: str = Field(alias="resourceId")
    file_content: Optional[str] = Field(alias="fileContent", default=None)
    file_name: Optional[str] = Field(alias="fileName", default=None)
