# Generated by ariadne-codegen
# Source: operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ListResources(BaseModel):
    resources: "ListResourcesResources"


class ListResourcesResources(BaseModel):
    total_count: int = Field(alias="totalCount")
    edges: list["ListResourcesResourcesEdges"]
    page_info: "ListResourcesResourcesPageInfo" = Field(alias="pageInfo")


class ListResourcesResourcesEdges(BaseModel):
    cursor: str
    node: "ListResourcesResourcesEdgesNode"


class ListResourcesResourcesEdgesNode(BaseModel):
    id: str
    state: str


class ListResourcesResourcesPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


ListResources.model_rebuild()
ListResourcesResources.model_rebuild()
ListResourcesResourcesEdges.model_rebuild()
