# Generated by ariadne-codegen
# Source: operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class RegisterResourceType(BaseModel):
    register_resource_type: "RegisterResourceTypeRegisterResourceType" = Field(
        alias="registerResourceType"
    )


class RegisterResourceTypeRegisterResourceType(BaseModel):
    success: bool
    resource_type: Optional["RegisterResourceTypeRegisterResourceTypeResourceType"] = (
        Field(alias="resourceType")
    )
    error: Optional["RegisterResourceTypeRegisterResourceTypeError"]


class RegisterResourceTypeRegisterResourceTypeResourceType(BaseModel):
    id: str
    name: str


class RegisterResourceTypeRegisterResourceTypeError(BaseModel):
    code: str
    message: str


RegisterResourceType.model_rebuild()
RegisterResourceTypeRegisterResourceType.model_rebuild()
