# Generated by ariadne-codegen
# Source: operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class TransitionResource(BaseModel):
    transition_resource: "TransitionResourceTransitionResource" = Field(
        alias="transitionResource"
    )


class TransitionResourceTransitionResource(BaseModel):
    success: bool
    resource: Optional["TransitionResourceTransitionResourceResource"]
    error: Optional["TransitionResourceTransitionResourceError"]


class TransitionResourceTransitionResourceResource(BaseModel):
    id: str
    state: str


class TransitionResourceTransitionResourceError(BaseModel):
    code: str
    message: str


TransitionResource.model_rebuild()
TransitionResourceTransitionResource.model_rebuild()
