apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kors.fullname" . }}-bff
  labels:
    app: bff
spec:
  replicas: {{ .Values.bff.replicaCount }}
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: "{{ .Values.bff.image.repository }}:{{ .Values.bff.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: NATS_URL
              value: {{ .Values.nats.url }}
            - name: SERVICE_NAME
              value: "kors-bff"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
