package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/haksolot/kors/examples/module-example/internal/graph/generated"
	"github.com/haksolot/kors/examples/module-example/internal/graph/model"
)

// Tools is the resolver for the tools field.
func (r *queryResolver) Tools(ctx context.Context) ([]*model.Resource, error) {
	tools, err := r.Store.ListAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Resource, 0, len(tools))
	for _, t := range tools {
		result = append(result, &model.Resource{Id: t.ID.String()})
	}
	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
