package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/haksolot/kors/examples/module-example/internal/graph/generated"
	"github.com/haksolot/kors/examples/module-example/internal/graph/model"
)

// Tools is the resolver for the tools field.
func (r *queryResolver) Tools(ctx context.Context) ([]*model.Resource, error) {
	panic(fmt.Errorf("not implemented: Tools - tools"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
