// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Query struct {
}

type Resource struct {
	ID       uuid.UUID `json:"id"`
	Diameter *float64  `json:"diameter,omitempty"`
	Length   *float64  `json:"length,omitempty"`
}

func (Resource) IsEntity() {}
